### PR TITLE
Some helpers backported from 0.4

### PR DESCRIPTION
**Pull request by ray66rus**
1. Backported getPrivateKeyFromPassword method
2. Backported convinient constructrors for Transaction, EscrowApproveOperation and CommentOperation classes

### CODE REVIEW

**Comment by ray66rus** [comment]
The better method would be to convert 0.4 branch for Android, but don't really have time for this :)

**Comment by marvin-we** [comment]
Hello @ray66rus ,

first things first: Thank you very much for pushing this change - I really appreciate it. (Could you tell me your name at steemit.com so that I may can do something for you too?)

> The better method would be to convert 0.4 branch for Android, but don't really have time for this :)

I totally agree on that as 0.4.0 also contains changes that improve the functionallity on Android a lot. My main point here is:
- Do you also use SteemJ for an android app like @ismelykh ? 
- As discussed in #64 , SteemJ is using some Java 8 features and it is planned to add some more (see #82 ). Java 8 is supported in Android versions above 7 which would only cover ~18% of the devices at the moment...  My question would be: Do you also need SteemJ to work with Java 7?

I am asking these questions because (as you already mentioned) adjusting everything for Java 7 is not the smallest task and will take some time. If you are now the second user of SteemJ who really needs SteemJ for Java 7 I am willing to invest some time to release a dedicated version of SteemJ 0.4.1 working with Java 7.

Depending on your answers I will accept the change :)

Thank you once again and best regards!

**Comment by ray66rus** [comment]
Hi. Sorry, for some reason I couldn't register at steemit - failed with verification :) Should try it again. I have an account at golos.io right now. Anyway - thanks for the suggestion.

Concerning your first questions - actually, it's the same project, so while technicaly there are two users trying to add steem functionality to native android application, you can consider two of us as one :)
Answer to the second question is yes. May be when this project would be production-ready there would be a lot of Android 7+ phones, but I'm inclined to be more optimistic about the development time.

But I think that it's anyway a good idea to make your library android-compatible. Maybe just not yet.

Anyway, I have a couple of suggestions that concers 0.4 branch as well as 0.3. I can make pull-requests to 0.3.3, or create issues (or pull requests) to 0.4 branch.

PS: Just found a bug in my current pull request

**Comment by marvin-we** [comment]
Hay ho :) Thank you once again for your feedback.

>  failed with verification :) Should try it again.

That could already be something I could do for you ;) Just send me the account name you would like to have at steemit.com and a way how I can send you the initial password.

> I have an account at golos.io right now

I would love to support golos.io too with SteemJ - Have you ever used SteemJ with Golos and do you know which changes would be required? I guess adding some new currency types and adding a way to skip the validation as suggested in #117 should do the trick.

> But I think that it's anyway a good idea to make your library android-compatible. Maybe just not yet.

I totally agree on that - Thats why I also removed the logging framework with SteemJ 0.4.0 which caused a lot of problems to get SteemJ working for Android. In general you and @ismelykh found a lot of mistakes and improvements in SteemJ, so I would really love to see you working also with newer versions.  So I changed the title of #64 a little bit and added it to the 0.4.1 milestone meaning that the target Java version for 0.4.1 is Java 7.

> Anyway, I have a couple of suggestions that concers 0.4 branch as well as 0.3. I can make pull-requests to 0.3.3, or create issues (or pull requests) to 0.4 branch.

Let me finish the issues I've already started to work on locally - After that I will start with the Java 7 changes immediatly and then you can submit your pull requests to the master branch, okay? :) 

Thank you once again for improving and pushing this project!

**Comment by ray66rus** [comment]
Thank's  again. I would be very grateful if you add an account for me :) I'd like to have there the same account name - ray66rus. The mail is the same - ray66rus@gmail.com so you can send a password to that email.

Actually I haven't try the library on golos.io. For now we are working mostly with the testnet - a lot of experimenting so don't want to add trash to production blockchain :)

**Comment by marvin-we** [comment]
Hay @ray66rus  - The account has been created and the information has been sent per mail.

> Actually I haven't try the library on golos.io. For now we are working mostly with the testnet - a lot of experimenting so don't want to add trash to production blockchain :)

We can continue this discussion per mail if you are interested in:
- Create SteemJ Update posts for the russion community
- Test SteemJ for Golos

Again, I would really appretiate both actions :P :)

Best regards!

**Pull request closed without merging**
